### ISSUE TITLE
Please Update the Module 

### ISSUE THREAD

**Issue by ProTechEx** [caffedrine/scaleway-whmcs#15]
Hey Caffedrine,

could please update your module to the current Scaleway API with new available scaleway products?

I could pay also for the work if you can provide me 100% complete and compatible module.

Kind regards

**Comment by blacklevel7** [comment]
Hey @caffedrine.

could please update your module to the current Scaleway API with new available scaleway products?

**Comment by caffedrine** [comment]
The products were updated!
